name: my_first_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/image.jpg
    - assets/images/foto.jpg
    - assets/images/gargantua.jpg
    - assets/images/cascada1.jpg
    - assets/images/cascada2.jpg
    - assets/images/cascada3.png
    - assets/images/cascada4.jpg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

